// 요약: 전체 레이아웃 (헤더, 폰트, Tailwind globals)

import './globals.css';
import Header from '@/components/layouts/Header';
import Footer from '@/components/layouts/Footer';
import Container from '@/components/layouts/Container';
import localFont from 'next/font/local';

const pretendard = localFont({
  src: [
    {
      path: './fonts/Pretendard-Regular.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/Pretendard-Medium.woff',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/Pretendard-SemiBold.woff',
      weight: '600',
      style: 'normal',
    },
    {
      path: './fonts/Pretendard-Bold.woff',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-pretendard',
  display: 'swap',
});


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${pretendard.variable} antialiased`} > 
        <div className="flex min-h-screen flex-col">
          {/* Header 영역 */}
          <Header />
          {/* Main 영역 */}
          <main className="flex-1"><Container>{children}</Container></main>
          {/* Footer 영역 */}
          <Footer />
        </div>
      </body>
    </html>
  );
}
